$(function(){window.wave_intervals;window.wave_data;window.selected_signals=[];window.low_limit=0;window.max_limit=30;read_vcd();var a=!1,h;$("canvas").on("contextmenu",function(){return!1});$("#myCanvas").mousedown(function(b){switch(b.which){case 1:if(draw_wave(wave_data),x=b.pageX-$("#myCanvas").offset().left-100,0<x&&650>x){x_interval=650/(max_limit-low_limit);time_interval=wave_data.time_info.duration/(wave_data.time_info.intervals-1);timeframe=(Math.floor(x/x_interval)+low_limit)*time_interval;
var g=0,e=document.getElementById("myCanvas"),m=e.height,q=document.getElementById("bufferCanvas"),d=36,n=q.getContext("2d");n.fillStyle="#000";n.strokeStyle="#000";n.font="12px 'Times New Roman'";$.each(window.selected_signals,function(a,b){$.each(window.wave_data[b],function(b,a){-1!=a&&(g=a);if(b>=timeframe)return!1});n.fillText("Value : "+g,15,d);d+=40});n.beginPath();n.strokeStyle="#4af";n.moveTo(x+100,0);n.lineTo(x+100,m-10);n.stroke();n.closePath();x_time=x-5*(timeframe.toString().length/2+
1);n.fillText(timeframe.toString()+wave_data.time_info.timescale,x_time+100,m-5);e.getContext("2d").drawImage(q,0,0);e=e.toDataURL("image/jpg");document.getElementById("myimage").innerHTML='<img src="'+e+'"/>'}case 3:a=!0,h=b.pageX}});$(document).mouseup(function(b){a&&(a=!1)});$("#myCanvas").mousemove(function(b){if(a){var g=b.pageX,e=Math.round((h-g)/10);h=g;temp_low_limit=low_limit+e;temp_max_limit=max_limit+e;0>temp_low_limit?low_limit=0:temp_max_limit>wave_intervals?(low_limit=wave_intervals-
(max_limit-low_limit),max_limit=wave_intervals):(low_limit=temp_low_limit,max_limit=temp_max_limit);draw_wave(wave_data)}x=b.pageX-$("#myCanvas").offset().left-100;if(0<x&&650>x){x_interval=650/(max_limit-low_limit);time_interval=wave_data.time_info.duration/(wave_data.time_info.intervals-1);timeframe=(Math.floor(x/x_interval)+low_limit)*time_interval;var m=0;b=document.getElementById("myCanvas");var g=b.height,e=document.getElementById("bufferCanvas"),q=36,d=b.getContext("2d");d.drawImage(e,0,0);
d.fillStyle="#000";d.strokeStyle="#000";d.font="12px 'Times New Roman'";$.each(window.selected_signals,function(a,b){$.each(window.wave_data[b],function(b,a){-1!=a&&(m=a);if(b>=timeframe)return!1});d.fillStyle="#ffa";d.fillRect(15,q-10,80,10);d.fillStyle="#000";d.fillText("Value : "+m,15,q);q+=40});d.beginPath();d.strokeStyle="#faa";d.moveTo(x+100,0);d.lineTo(x+100,g-10);d.stroke();d.closePath();x_time=x-5*(timeframe.toString().length/2+1);d.fillText(timeframe.toString()+wave_data.time_info.timescale,
x_time+100,g-5)}});$("#myCanvas").mouseout(function(a){a=document.getElementById("myCanvas");var g=document.getElementById("bufferCanvas");a.getContext("2d").drawImage(g,0,0)});$("#slider_button").mousedown(function(a){$("#slider_info").show(400);$("body").on("mousemove",function(a){offset=a.pageX-$("#slider_main").offset().left-$(".slider_button").outerWidth()/2;offset=Math.round(offset);0>offset&&(offset=1);100<offset&&(offset=100);$("#slider_button").css("left",offset+"px");$("#slider_info").css("left",
offset+"px");$("#simulation_zoom").val(offset);draw_wave(wave_data);$("#slider_info").html(offset+"%");a.preventDefault()}).on("mouseup",function(){$("body").unbind("mousemove");$("#slider_info").hide(400)})})});
function read_vcd(){$.ajax({type:"GET",url:"functions.php",data:"read_vcd=1",dataType:"json",success:function(a){var h,b,g=0;max_limit=30>a.time_info.intervals?a.time_info.intervals:30;wave_intervals=a.time_info.intervals;wave_data=a;$("#signals").append("<div id='module_none'></div>");$.each(a,function(e,m){m.name&&"time_info"!=e&&(m.module?(h=m.module.split("_-_"),b=create_modules(h)):b="none",$("#module_"+b).append(m.name),$("#module_"+b).append("<span id='signal_"+g+"' class='pointer'> =></span>"),
"'"==e?$("#module_"+b).append("<input type='hidden' id='signal_"+g+"_val' value=\"'\" /><br/>"):$("#module_"+b).append("<input type='hidden' id='signal_"+g+"_val' value='"+e+"' /><br/>"),$("#signal_"+g).click(function(b){b=$("#"+b.target.id+"_val").val();-1==selected_signals.indexOf(b)&&(selected_signals[selected_signals.length]=b,draw_wave(a))}),g++)})}})}
function create_modules(a){var h=a.pop();return h?(0==$("#module_"+h).length&&(parent_module=create_modules(a),a=-1==parent_module?$("#signals"):$("#module_"+parent_module),a.append("<br/><span id='span_module_"+h+"' class='bold pointer'>+ "+h+"</span><br/>"),a.append("<div id='module_"+h+"' class='hidden'></div>"),$("#span_module_"+h).click(function(){$("#module_"+h).toggleClass("hidden")})),h):-1}
function draw_wave(a){var h=1,b=10,g=-1,e=-1,m=1,q=0,d=0,n=1,v=-1,w=1,u=15,y=a.time_info.duration/(a.time_info.intervals-1);max_limit=low_limit+Math.round(a.time_info.intervals*($("#simulation_zoom").val()/100));max_limit>a.time_info.intervals&&(low_limit-=max_limit-a.time_info.intervals,max_limit=a.time_info.intervals);var m=max_limit-low_limit,m=9<m?Math.round(m/9):1,l=document.getElementById("myCanvas"),r=95,p=l.width;l.height=40*window.selected_signals.length+40;var z=l.height,f=5,k=20,c=l.getContext("2d");
c.fillStyle="#fff";c.fillRect(0,0,p,z);c.fillStyle="#000";c.strokeStyle="#000";c.font="12px 'Times New Roman'";$.each(window.selected_signals,function(l,p){c.moveTo(f,k);c.fillText(a[p].name,f,k);f+=r;r=650/(max_limit-low_limit);$.each(a[p],function(l,t){-1!=t&&(e=t);!isNaN(l)&&l>=low_limit*y&&l<=max_limit*y&&(c.strokeStyle="#000",1==h&&(0==q?(u=15==u?0:15,c.beginPath(),c.strokeStyle="#aaa",c.moveTo(f,0),c.lineTo(f,z-40+u),c.stroke(),c.closePath(),x_time=f-5*(l.length/2+1),c.fillText(l+a.time_info.timescale,
x_time,z-35+u),q=m):q--),c.beginPath(),c.strokeStyle="#000",1==a[p].length?(-1==t&&(t=e),1==t?b=-10:0==t?b=10:"U"==t&&(b=0,c.strokeStyle="#f00"),-1==g&&(g=b),c.moveTo(f,k+b),c.lineTo(f+r,k+b),c.moveTo(f,k+g),c.lineTo(f,k+b)):(-1==t?d=r+d:(1!=n&&(value_length=v.match(/bU.*/g)?10*v.length:8*v.length,value_length<d&&c.fillText(v,f-d+5,k+5)),d=r,c.moveTo(f,k+10),c.lineTo(f,k-10),c.moveTo(f+1.5,k-1.5),c.arc(f,k,3,0,2*Math.PI,!1)),e.match(/bU.*/g)&&(c.strokeStyle="#f00"),c.moveTo(f,k+10),c.lineTo(f+r,k+
10),c.moveTo(f,k-10),c.lineTo(f+r,k-10)),f+=r,g=b,c.stroke(),c.closePath(),n=0);(l>=max_limit*y||l==a.time_info.duration)&&1==w&&(w=0,1<a[p].length&&(value_length=e.match(/bU.*/g)?10*e.length:8*e.length,value_length<d&&c.fillText(e,f-d+5,k+5)),u=15==u?0:15);v=e});k+=40;f=5;r=95;e=g=-1;h=0;n=1;d=0;w=1});p=l.toDataURL("image/jpg");document.getElementById("myimage").innerHTML='<img src="'+p+'"/>';p=document.getElementById("bufferCanvas");p.width=l.width;p.height=l.height;context=p.getContext("2d");context.drawImage(l,
0,0)};